# Generated by Django 4.1.7 on 2023-06-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_user_email'),
        ('collabrate1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabnote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='signin.user'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('grpname', 'user')},
        ),
    ]
