# Generated by Django 4.1.7 on 2023-04-27 04:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_alter_shared_with_me_notebook_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_with_me',
            name='notebook_slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, null=True, populate_from='notebook_name'),
        ),
    ]
