# Generated by Django 4.1.7 on 2023-04-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_alter_shared_with_me_notebook_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_with_me',
            name='notebook_slug',
        ),
    ]
