# Generated by Django 4.1.7 on 2023-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
