# Generated by Django 4.1.7 on 2023-03-23 12:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='notes_name'),
        ),
    ]
