# Generated by Django 4.1.7 on 2023-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
