# Generated by Django 4.1.7 on 2023-04-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_bookmark_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='attach',
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.notes')),
            ],
        ),
    ]
