# Generated by Django 4.1.7 on 2023-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_shared_with_me_notebook_slug'),
        ('notes', '0006_remove_notes_attach_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('notes_name', 'notebook')},
        ),
    ]
