# Generated by Django 4.1.7 on 2023-04-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_notes_notes_name_alter_notes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together=set(),
        ),
    ]
