# Generated by Django 4.1.7 on 2023-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user_alter_task_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_time',
        ),
        migrations.AddField(
            model_name='task',
            name='time_diff',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(),
        ),
    ]
