# Generated by Django 4.1.7 on 2023-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_task_time_task_time_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
