# Generated by Django 4.1.7 on 2023-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
