# Generated by Django 4.1.7 on 2023-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_task_task_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_diff',
        ),
        migrations.AddField(
            model_name='task',
            name='task_created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
