# Generated by Django 4.1.7 on 2023-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_task_task_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_diff',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
