# Generated by Django 4.1.7 on 2023-04-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_user_email'),
        ('task', '0012_task_time_diff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_name', 'user')},
        ),
    ]
