# Generated by Django 4.1.7 on 2023-03-22 11:39

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared_with_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='@gmail.com', max_length=20, null=True)),
                ('notebook_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=25, unique=True)),
                ('book_created_on', models.DateTimeField(auto_now_add=True)),
                ('book_last_modified', models.DateTimeField(auto_now=True)),
                ('notebook_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='book_name')),
                ('bookmark_notebook', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.user')),
            ],
        ),
    ]
