# Generated by Django 4.1.7 on 2023-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_with_me',
            name='note_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shared_with_me',
            name='notebook_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
