# Generated by Django 4.1.7 on 2023-03-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_user_email'),
        ('notebook', '0002_shared_with_me_note_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together={('book_name', 'user')},
        ),
    ]
