# Generated by Django 4.1.7 on 2023-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_notebook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='book_name',
            field=models.CharField(max_length=25),
        ),
    ]
