# Generated by Django 4.1.7 on 2023-03-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_user_email'),
        ('notebook', '0004_alter_notebook_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_with_me',
            name='note_name',
        ),
        migrations.AddField(
            model_name='shared_with_me',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='signin.user'),
        ),
    ]
