# Generated by Django 4.1.7 on 2023-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_remove_shared_with_me_note_name_shared_with_me_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_with_me',
            name='shared_by',
            field=models.CharField(default='@gmail.com', max_length=20),
        ),
    ]
