# Generated by Django 4.1.7 on 2023-04-27 04:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_shared_with_me_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_with_me',
            name='notebook_slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='notebook_name'),
        ),
    ]
